---
title: "Untitled"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(library("tidyverse"))

pWAS.list <- readRDS('pWAS.list.rds')

pwas.time <- function(x){
  dot.for.dash <- function(x) sub("[-_]",".",x)
  d.nought <- function(x) sub("d0.*","D0",x,ignore.case=TRUE)
  d42.to.wk6 <- function(x) sub("^d4[25]$","wk6",x)
  pwas.unit <- function(x) c(WK = "WEEKS", M="MONTHS", Y="YEARS", D="DAYS")[
    sub("[[:digit:]].*$","",x)]
  pwas.timeval <- function(x) sub("[[:alpha:]]+","",x)
  x <- as.character(x)
  tm <- toupper( d42.to.wk6( d.nought( dot.for.dash( x ))))
  res <- paste(pwas.timeval( tm ), pwas.unit( tm ))
  res[ res == "18 MONTHS" ]  <- "1.5 YEARS"
  res[ res == "30 MONTHS" ]  <- "2.5 YEARS"
  res[ res == "42 MONTHS" ]  <- "3.5 YEARS"
  res[ res == "32 DAYS" ]  <- "1 MONTHS"
  res[ res %in% c("45 DAYS", "42 DAYS") ]  <- "1.5 MONTHS"
  res[ res == "6 WEEKS" ]  <- "1.5 MONTHS"
  res
}

tabs <-
  imap(pWAS.list,
         function(pt,x){
           output_list = list()
           time <- pwas.time(pt$d$timePoint)
           table <- table(pt$d$posid,factor(time,unique(time)))>0
           table_sum <- crossprod(table)
           counts <- data.frame(table) %>% summarise_all(~sum(.)) %>% simplify()
           names(counts) <-  colnames(table_sum)
           output_list$table  <- table_sum
           output_list$counts <- counts
           output_list$name <- x
 #          browser()
           return(output_list)
         })

long_tables <- imap(tabs,function(tab,name){
  #browser()
  factor_order <- c("0 DAYS","1 MONTHS","1.5 MONTHS","3 MONTHS","6 MONTHS","9 MONTHS",
                    "1 YEARS","1.5 YEARS","2 YEARS","2.5 YEARS","3 YEARS",
                    "3.5 YEARS","4 YEARS","4.5 YEARS","5 YEARS","6 YEARS")
  as.data.frame(tab$table) %>%
    rownames_to_column(var = "y") %>% 
    #  mutate(across(where(is.numeric),~./max(.))) %>%
    pivot_longer(!y,values_to='val', names_to='x') %>%
    mutate(x=fct_relevel(x,factor_order[factor_order %in% x])) %>%
    mutate(y=fct_relevel(as.factor(y),factor_order[factor_order %in% y])) %>%
    mutate(y_count=tab$counts[as.character(y)],x_count=tab$counts[as.character(x)]) %>%
    mutate(jaccard=(val/(x_count+y_count-val))) %>%
    mutate(sample_name=name) %>%
    mutate(x_s=paste(x,sample_name),y_s=paste(y,sample_name))
})

factor_order <- c("0 DAYS","1 MONTHS","1.5 MONTHS","3 MONTHS","6 MONTHS","9 MONTHS",
                  "1 YEARS","1.5 YEARS","2 YEARS","2.5 YEARS","3 YEARS",
                  "3.5 YEARS","4 YEARS","4.5 YEARS","5 YEARS","6 YEARS")
long_names <- names(long_tables)
factor_order_plus <- as.vector(outer(factor_order, long_names, FUN = "paste"))

inv_paste <- function(x,y) paste(y,x)
inv_get_date <- function(x,y) return(y)
factor_order_per_date <- as.vector(outer(long_names,factor_order, FUN = inv_paste))


```


## Including Plots

You can also embed plots, for example: 
$$
E = mc^2
$$

```{r pressure, echo=FALSE}
reduce(long_tables,rbind) %>% 
  mutate(x_s=fct_relevel(x_s,factor_order_per_date[factor_order_per_date %in% x_s])) %>%
  mutate(y_s=fct_relevel(y_s,factor_order_per_date[factor_order_per_date %in% y_s])) %>%
ggplot( aes(x_s,y_s, fill= jaccard)) + 
  geom_tile() +
  scale_fill_binned(breaks = c(0.001, 0.2, 0.4,0.6),low="white", high="blue",show.limits = TRUE) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90,size=4),
        axis.title.x=element_blank(),
        axis.title.y=element_blank()) +
  scale_x_discrete()
  #  xlab("Sample") +
  #  labs(fill='Dilution \nat threshold',
  #       title = "Quiescent") +
  #  My_Theme +
  coord_equal() 

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
